// Server error codes → something a player can act on. Unknown codes fall
// back to the code itself with dashes turned into spaces.
const MESSAGES = {
    'room-not-found': 'That room no longer exists.',
    'room-full': 'The room is full — you are watching as a spectator.',
    'not-host': 'Only the host can do that.',
    'need-2-players': 'You need at least 2 players to start.',
    'not-your-turn': "It's not your turn.",
    'not-your-turn-to-roll': "You can't roll right now.",
    'resolve-debt-first': 'Settle your debt first.',
    'pay-debt-first': 'Pay what you owe before building or unmortgaging.',
    'roll-first': 'Roll the dice first.',
    'roll-again-doubles': 'You rolled doubles — roll again.',
    'insufficient': "You don't have enough cash.",
    'no-debt': 'You have nothing to pay.',
    'not-buyable': "There's nothing to buy right now.",
    'pay-before-rolling': 'You can only pay the fine before rolling.',
    'use-before-rolling': 'You can only use the card before rolling.',
    'no-card': "You don't have a Get Out Free card.",
    'not-owner': "You don't own that.",
    'already-mortgaged': "It's already mortgaged.",
    'not-mortgaged': "It isn't mortgaged.",
    'sell-buildings-first': 'Sell the buildings in that colour group first.',
    'group-has-buildings': 'Sell the buildings in that colour group first.',
    'group-has-mortgaged': 'Unmortgage the whole colour group before building.',
    'not-monopoly': 'You need the whole colour group to build.',
    'uneven-build': 'Build evenly — add to the property with the fewest houses first.',
    'uneven-sell': 'Sell evenly — remove from the property with the most houses first.',
    'max-built': 'That already has a hotel.',
    'no-houses': 'The bank has run out of houses.',
    'no-hotels': 'The bank has run out of hotels.',
    'mortgaged': "You can't build on a mortgaged property.",
    'below-min': 'Your bid has to beat the current bid.',
    'already-passed': "You've already passed on this auction.",
    'already-top-bidder': "You're already the top bidder.",
    'top-bidder-cannot-pass': "You're the top bidder — you can't pass.",
    'bad-amount': 'Enter a number.',
    'trade-already-open': 'You already have an open trade with that player.',
    'cannot-trade-with-yourself': "You can't trade with yourself.",
    'empty-trade': 'Add something to the trade first.',
    'from-insufficient': 'Not enough cash for that offer.',
    'to-insufficient': "They don't have that much cash.",
    'from-not-owner': "You don't own one of those properties any more.",
    'to-not-owner': "They don't own one of those properties any more.",
    'from-no-card': "You don't have that jail card.",
    'to-no-card': "They don't have that jail card.",
    'player-not-idle': "They're back online (or haven't been gone long enough).",
    'slow-down': "You're sending messages too fast.",
    'color-taken': 'Someone already has that colour.',
    'unknown-board': "That board doesn't exist.",
    'server-error': 'Something went wrong on the server.',
};

export function errorText(code) {
    if (typeof code !== 'string') return 'Something went wrong.';
    return MESSAGES[code] || code.replace(/-/g, ' ');
}
